### PR TITLE
Add tests for pinning

### PR DESCRIPTION
**Pull request by wpoely86**

### CODE REVIEW

**Comment by wpoely86** [comment]
@boegel please review

**Comment by boegel** [comment]
@wpoely86 I guess it makes sense to also test the default (i.e. without touching `pinning_override_type`)?

**Comment by wpoely86** [comment]
The function is not called unless asked. 

```python
        if self.pinning_override_type is not None:
            self.mpirun_cmd.add(self.pinning_override())
```

**Comment by boegel** [comment]
Nevermind, `pinning_override()` is never called when `pinning_override_type` is the default `None`, so good to go...

**Pull request merged**
