### PR TITLE
fix --hybrid when using (recent) OpenMPI

### LINKED ISSUE #174: "mympirun --hybrid" doesn't work as expected with OpenMPI 3.x & newer
```
#!/bin/bash
#PBS -l nodes=2:ppn=all
module load foss/2019b
module load vsc-mympirun

mympirun --hybrid 1 hostname
```

expected result: two different hostnames being printed

observed result: two **identical** hostnames being printed

This works fine with `foss/2018a` & older (OpenMPI 2.x).

### PR DESCRIPTION
**Pull request by boegel**
fixes #174

### CODE REVIEW

**Comment by stdweird** [comment]
@boegel looks ok, buttests fail

**Comment by boegel** [comment]
Seems like one of the tests hardcodes a particular order, which isn't always preserved?

```
======================================================================
FAIL: test_openmpi4 (test.end2end.TestEnd2End)
Test dry run with OpenMPI 4.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/hpcugent_github.com/jobs/vsc-mympirun/branches/PR-175/workspace/test/end2end.py", line 504, in test_openmpi4
    self.assertTrue(regex.search(out), "Pattern '%s' should be found in: %s" % (regex.pattern, out))
AssertionError: None is not true : Pattern '^fake mpirun called with args:.*--mca pml ucx --mca btl \^uct' should be found in: fake mpirun called with args: -machinefile /tmp/tmpSXf3v8/.mympirun_aye8x3/12345_20201106_224538/nodes --mca orte_keep_fqdn_hostnames 1 --mca btl ^uct --mca MKL_NUM_THREADS 1 --mca pml ucx -np 2 -x PATH -x PYTHONPATH -x OMP_NUM_THREADS mpi_hello
```

**Comment by stdweird** [comment]
@boegel well, you did change a `super` invocation, so maybe that part messes some stuff around?

**Comment by boegel** [comment]
@stdweird Fixed.

**Review by stdweird — APPROVED** [review]

**Pull request merged**
